server:
  port: 8010

spring:
  application:
    name: dubbo-provider-product
  profiles:
    active: peer2
dubbo:
  scan:
    # 扫描暴露服务的实例
    base-packages: com.xiaopantx.dubbo.service
  protocol:
    # RPC 协议
    name: dubbo
    # 服务端口
    port: 6666
    # 服务地址
    host: localhost
  registry:
    # 注册中心
    address: zookeeper://192.168.1.100:2181